function [x0] = calc_init_state(theta_6, theta_7, theta_10)
    % given theta 6, 7 and 10 from the patient parameter vector, we
    % calculate the initial state based on the information provided in Jost et al. 2020
    x0 = [0;...
        0;...
        0;...
        theta_6*theta_10/theta_7;...
        theta_6*theta_10/theta_7;...
        theta_6*theta_10/theta_7;...
        theta_6*theta_10/theta_7;...
        theta_6];
end